### PR TITLE
Preview

### PR DESCRIPTION
**Pull request by redhoteggplant**

### CODE REVIEW

**Comment by redhoteggplant** [comment]
Hey Eugene we've been working on it (focusing on messageText first) but have some errors. Right now we have an issue with calling xhttp.send() with our JSON object. We printed our req.body and it gives { '{"line1":"13","line2":"","mode":1}': '' } instead of just {"line1":"13","line2":"","mode":1}. We'd appreciate some help with debugging sorry T_T

**Comment by spaceraccoon** [comment]
@tanyichern @redhoteggplant 

Ok there are several errors:

1. Since the `onclick` event depends on `event` as an argument, remember to use `button.btn.btn-primary(type='button', id='preview-button', onclick='preview(event)') Preview` and `var preview = function(event) {` instead.
2. Since you are sending JSON instead of a form data, you have to use `xhttp.setRequestHeader('Content-type', 'application/json')` instead
3. For the preview route, since you are using a `switch` statement, remember to add a `break` at the end of each case else it will try to run all cases.
4. Since you are returning JSON, you don't use `res.send`. Use something like ```
res.status(200).json({
            errors: null,
            message
          })
``` for a successful return and ```
res.status(400).json({
          errors,
          message: null
          })
``` for failure
5. When receiving the JSON response from the server, remember that you are only getting a string, not a JSON object. So you need to do something like```
 var response = JSON.parse(this.responseText)
            console.log(response.message)
            previewDisplay(response.message)
```

I'm meeting them tomorrow so do try to get it done by tonight! This should fix your server side issues.

**Comment by tanyichern** [comment]
Would appreciate quick help on xhttp, for messageText

error in input allows the alert to pop up, but correct input doesn't enter the block of the second if, so JSON.parse(this.responseText) doesn't seem to run and unable to console.log

**Comment by spaceraccoon** [comment]
@tanyichern It does work enter the second if - just console.log(response.message) to check.

**Comment by spaceraccoon** [comment]
Also strange bug... all the selection items in the data mode disappear when you generate a preview.

**Comment by spaceraccoon** [comment]
Manual mode is not working as well

**Comment by tanyichern** [comment]
Unable to fix data because no smarking API key, can we get access?

**Comment by spaceraccoon** [comment]
Sent it to you! Looking good!

**Comment by spaceraccoon** [comment]
Also not sure if I missed something but the server sending back a title seems extraneous.

**Comment by tanyichern** [comment]
Removed titles in response. Can't replicate your error in data mode? Data mode works fine for me, both generating and submitting.

**Pull request merged**
